services:
  ex_project_postgres:
    container_name: ex_project_postgres
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ex_project_repo
    # network_mode: host
    volumes:
      - /home/docker-data/ex_project_postgres:/var/lib/postgresql/data
    healthcheck:
      test: [ CMD-SHELL, pg_isready -U postgres ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  ex_project_postgres:
